{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "vulnerability-scan.fullname" . }}
  labels:
    {{- include "vulnerability-scan.labels" . | nindent 4 }}
rules:
- apiGroups:
  - radix.equinor.com
  resources:
  - radixdeployments
  verbs:
  - list
  - get
  - watch
- apiGroups:
  - ''
  resources:
  - secrets
  verbs:
  - get
{{- end}}