name: Deploy Database

on:
  push:
    branches: [main, release]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        target:
        - name: "dev"
          ref: "refs/heads/master"
          client-id: "0f26a8a6-3593-4eb3-9d74-b2fb814c6fee"
          server: "sql-radix-vulnerability-scan-dev.database.windows.net"

        - name: "playground"
          ref: "refs/heads/release"
          client-id: "8d02c39d-6757-4977-9ad3-017889fe3f45"
          server: "sql-radix-vulnerability-scan-playground.database.windows.net"

        - name: "platform"
          ref: "refs/heads/release"
          client-id: "to be decided" #FIXME
          server: "sql-radix-vulnerability-scan-prod.database.windows.net"

        - name: "c2"
          ref: "refs/heads/release"
          client-id: "to be decided" #FIXME
          server: "sql-radix-vulnerability-scan-c2.database.windows.net"

    env:
      connection: >-
        Server=${{matrix.target.server}};
        Initial Catalog=radix-vulnerability-scan;
        Authentication=Active Directory Default; 
        Encrypt=True;
        TrustServerCertificate=False;
        Connection Timeout=30;

    steps:
      - uses: actions/checkout@v4
        if: matrix.target.ref == github.ref

      - uses: azure/login@v1
        if: matrix.target.ref == github.ref
        with:
          client-id: ${{matrix.target.client-id}}
          tenant-id: "3aa4a235-b6e2-48d5-9195-7fcf05b459b0"
          allow-no-subscriptions: true

      - uses: azure/sql-action@v2.2.1
        if: matrix.target.ref == github.ref
        with:
          connection-string: ${{env.connection}}
          path: './azure-infrastructure/sql-scripts/predeploy.sql'

      - uses: azure/sql-action@v2.2.1
        if: matrix.target.ref == github.ref
        with:
          connection-string: ${{env.connection}}
          path: './azure-infrastructure/sql-scripts/roles.sql'

      - uses: azure/sql-action@v2.2.1
        if: matrix.target.ref == github.ref
        with:
          connection-string: ${{env.connection}}
          path: './azure-infrastructure/sql-scripts/types.sql'

      - uses: azure/sql-action@v2.2.1
        if: matrix.target.ref == github.ref
        with:
          connection-string: ${{env.connection}}
          path: './azure-infrastructure/sql-scripts/tables.sql'

      - uses: azure/sql-action@v2.2.1
        if: matrix.target.ref == github.ref
        with:
          connection-string: ${{env.connection}}
          path: './azure-infrastructure/sql-scripts/views.sql'

      - uses: azure/sql-action@v2.2.1
        if: matrix.target.ref == github.ref
        with:
          connection-string: ${{env.connection}}
          path: './azure-infrastructure/sql-scripts/procedures.sql'
