name: Deploy ARM

on:
  push:
    branches: [main, release]

permissions:
  actions: read
  checks: read
  contents: read
  deployments: read
  id-token: write
  issues: read
  discussions: read
  packages: read
  pages: read
  pull-requests: read
  repository-projects: read
  security-events: read
  statuses: read

jobs:
  deploy-sql-server-main:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    env:
      RESOURCE_GROUP: vulnerability-scan
      DB_NAME: radix-vulnerability-scan
      SQL_ADMIN_USER_NAME: radix
      FIREWALL_RULE_NAME: githubRunnerIp
      ADMIN_GROUP_NAME: 'Radix Platform Developers'
      ADMIN_GROUP_ID: "a5dfa635-dc00-4a28-9ad9-9e7f1e56919d"
    steps:
      - uses: actions/checkout@v3
      - name: Login for dev
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID_DEV }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID_DEV }}
      - name: Define variables for dev
        run: |
          echo "SQL_SERVER_NAME=sql-radix-vulnerability-scan-dev" >> $GITHUB_ENV
          echo "KEY_VAULT_NAME=radix-vault-dev" >> $GITHUB_ENV
          echo "SQL_LOG_STORAGE_NAME=radixsqllogsdev" >> $GITHUB_ENV
      - uses: Azure/get-keyvault-secrets@v1
        with:
          keyvault: ${{ env.KEY_VAULT_NAME }}
          secrets: 'radix-vulnerability-scan-db-admin'
        id: adminPassword
      - name: Deploy SQL Server and DB
        env:
          DEPLOY_NAME: radix-vulnerability-scan-db-deploy-dev
        run: |
          # Get Storage Account ID for sql logs
          storageId=$(az storage account show --name "$SQL_LOG_STORAGE_NAME" --query "id" --output tsv)

          az deployment group create -g "$RESOURCE_GROUP" -n "$DEPLOY_NAME" \
            --template-file ./.azure-infrastructure/azuredeploy.json \
            --parameters serverName="$SQL_SERVER_NAME" \
            --parameters databaseName="$DB_NAME" \
            --parameters administratorLoginPassword="${{ steps.adminPassword.outputs.radix-vulnerability-scan-db-admin }}" \
            --parameters administratorLogin="$SQL_ADMIN_USER_NAME" \
            --parameters adminGroupName="$ADMIN_GROUP_NAME" \
            --parameters adminGroupId="$ADMIN_GROUP_ID" \
            --parameters storageAccountId=$storageId

      - name: Whitelist Runner IP in firewalls
        shell: pwsh
        run: |
          $runnerIp = (Invoke-WebRequest -uri "http://ifconfig.me/ip").Content
          az sql server firewall-rule create `
            --end-ip-address $runnerIp `
            --start-ip-address $runnerIp `
            --name ${env:FIREWALL_RULE_NAME} `
            --resource-group ${env:RESOURCE_GROUP} `
            --server ${env:SQL_SERVER_NAME}
      - name: Creating DB schema and tables
        shell: pwsh
        run: |
          Set-PSRepository -Name "PSGallery" -InstallationPolicy Trusted
          Install-Module -Name SqlServer

          $targetSqlServerFQDN = "$(az sql server show -n ${env:SQL_SERVER_NAME} -g ${env:RESOURCE_GROUP} | jq -r .fullyQualifiedDomainName)"

          Invoke-Sqlcmd -InputFile ./.sql-scripts/roles.sql -ServerInstance $targetSqlServerFQDN -Database ${env:DB_NAME} -Username ${env:SQL_ADMIN_USER_NAME} -password ${{ steps.adminPassword.outputs.radix-vulnerability-scan-db-admin }}
          Invoke-Sqlcmd -InputFile ./.sql-scripts/types.sql -ServerInstance $targetSqlServerFQDN -Database ${env:DB_NAME} -Username ${env:SQL_ADMIN_USER_NAME} -password ${{ steps.adminPassword.outputs.radix-vulnerability-scan-db-admin }}
          Invoke-Sqlcmd -InputFile ./.sql-scripts/tables.sql -ServerInstance $targetSqlServerFQDN -Database ${env:DB_NAME} -Username ${env:SQL_ADMIN_USER_NAME} -password ${{ steps.adminPassword.outputs.radix-vulnerability-scan-db-admin }}
          Invoke-Sqlcmd -InputFile ./.sql-scripts/procedures.sql -ServerInstance $targetSqlServerFQDN -Database ${env:DB_NAME} -Username ${env:SQL_ADMIN_USER_NAME} -password ${{ steps.adminPassword.outputs.radix-vulnerability-scan-db-admin }}
      - name: Blacklist Runner IP in firewalls
        shell: pwsh
        if: ${{ always() }}
        run: |
          az sql server firewall-rule delete `
            --name ${env:FIREWALL_RULE_NAME} `
            --resource-group ${env:RESOURCE_GROUP} `
            --server ${env:SQL_SERVER_NAME}

  deploy-sql-server-release:
    if: github.ref == 'refs/heads/release'
    runs-on: ubuntu-latest
    env:
      RESOURCE_GROUP: vulnerability-scan
      DB_NAME: radix-vulnerability-scan
      SQL_ADMIN_USER_NAME: radix
      FIREWALL_RULE_NAME: githubRunnerIp
      ADMIN_GROUP_NAME: 'Radix Platform Developers'
      ADMIN_GROUP_ID: "a5dfa635-dc00-4a28-9ad9-9e7f1e56919d"
    steps:
      - uses: actions/checkout@v3
      - name: Login for dev
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID_DEV }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID_DEV }}
      - name: Define variables for playground
        run: |
          echo "SQL_SERVER_NAME=sql-radix-vulnerability-scan-playground" >> $GITHUB_ENV
          echo "KEY_VAULT_NAME=radix-vault-dev" >> $GITHUB_ENV
          echo "SQL_LOG_STORAGE_NAME=radixsqllogsdev" >> $GITHUB_ENV
      - uses: Azure/get-keyvault-secrets@v1
        with:
          keyvault: ${{ env.KEY_VAULT_NAME }}
          secrets: 'radix-vulnerability-scan-db-admin-playground'
        id: adminPassword
      - name: Deploy SQL Server and DB
        env:
          DEPLOY_NAME: radix-vulnerability-scan-db-deploy-playground
        run: |
          # Get Storage Account ID for sql logs
          storageId=$(az storage account show --name "$SQL_LOG_STORAGE_NAME" --query "id" --output tsv)

          az deployment group create -g "$RESOURCE_GROUP" -n "$DEPLOY_NAME" \
            --template-file ./.azure-infrastructure/azuredeploy.json \
            --parameters serverName="$SQL_SERVER_NAME" \
            --parameters databaseName="$DB_NAME" \
            --parameters administratorLoginPassword="${{ steps.adminPassword.outputs.radix-vulnerability-scan-db-admin-playground }}" \
            --parameters administratorLogin="$SQL_ADMIN_USER_NAME" \
            --parameters adminGroupName="$ADMIN_GROUP_NAME" \
            --parameters adminGroupId="$ADMIN_GROUP_ID" \
            --parameters storageAccountId=$storageId

      - name: Whitelist Runner IP in firewalls
        shell: pwsh
        run: |
          $runnerIp = (Invoke-WebRequest -uri "http://ifconfig.me/ip").Content
          az sql server firewall-rule create `
            --end-ip-address $runnerIp `
            --start-ip-address $runnerIp `
            --name ${env:FIREWALL_RULE_NAME} `
            --resource-group ${env:RESOURCE_GROUP} `
            --server ${env:SQL_SERVER_NAME}
      - name: Creating DB schema and tables
        shell: pwsh
        run: |
          Set-PSRepository -Name "PSGallery" -InstallationPolicy Trusted
          Install-Module -Name SqlServer

          $targetSqlServerFQDN = "$(az sql server show -n ${env:SQL_SERVER_NAME} -g ${env:RESOURCE_GROUP} | jq -r .fullyQualifiedDomainName)"

          Invoke-Sqlcmd -InputFile ./.sql-scripts/roles.sql -ServerInstance $targetSqlServerFQDN -Database ${env:DB_NAME} -Username ${env:SQL_ADMIN_USER_NAME} -password ${{ steps.adminPassword.outputs.radix-vulnerability-scan-db-admin-playground }}
          Invoke-Sqlcmd -InputFile ./.sql-scripts/types.sql -ServerInstance $targetSqlServerFQDN -Database ${env:DB_NAME} -Username ${env:SQL_ADMIN_USER_NAME} -password ${{ steps.adminPassword.outputs.radix-vulnerability-scan-db-admin-playground }}
          Invoke-Sqlcmd -InputFile ./.sql-scripts/tables.sql -ServerInstance $targetSqlServerFQDN -Database ${env:DB_NAME} -Username ${env:SQL_ADMIN_USER_NAME} -password ${{ steps.adminPassword.outputs.radix-vulnerability-scan-db-admin-playground }}
          Invoke-Sqlcmd -InputFile ./.sql-scripts/procedures.sql -ServerInstance $targetSqlServerFQDN -Database ${env:DB_NAME} -Username ${env:SQL_ADMIN_USER_NAME} -password ${{ steps.adminPassword.outputs.radix-vulnerability-scan-db-admin-playground }}
      - name: Blacklist Runner IP in firewalls
        shell: pwsh
        if: ${{ always() }}
        run: |
          az sql server firewall-rule delete `
            --name ${env:FIREWALL_RULE_NAME} `
            --resource-group ${env:RESOURCE_GROUP} `
            --server ${env:SQL_SERVER_NAME}