name: radix-vulnerability-scanne-pr
on:
  pull_request:
    branches:
    - master
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build docker image
      env:
        REF: ${{ github. sha }}
      run: make build
  