name: Pull request
on:
  pull_request:
    branches:
    - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build docker image
      env:
        REF: ${{ github. sha }}
      run: make build

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      - name: Install dependencies
        run: go mod download
      - name: Install GolangCI Lint
        run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.55.2

      - name: golangci-lint
        run: golangci-lint run --timeout=30m --max-same-issues=0 --out-format=github-actions

  test:
    name: Unit Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      - name: Install dependencies
        run: go mod download
      - name: Run Tests
        run: go test -cover `go list ./... | grep -v 'pkg/client'`

  test-roles:
    runs-on: ubuntu-20.04

    env:
      connection: >-
        Server=sql-radix-vulnerability-scan-dev.database.windows.net
        Initial Catalog=radix-vulnerability-scan;
        Authentication=Active Directory Default; 
        Encrypt=True;
        TrustServerCertificate=False;
        Connection Timeout=30;

    steps:
      - uses: actions/checkout@v4

      - uses: azure/login@v1
        with:
          client-id: "a23b30b8-3faa-42a1-817e-6cd097a620f1"
          tenant-id: "3aa4a235-b6e2-48d5-9195-7fcf05b459b0"
          allow-no-subscriptions: true

      - uses: azure/sql-action@v2.2.1
        with:
          connection-string: ${{env.connection}}
          path: './azure-infrastructure/sql-scripts/roles.sql'
          arguments: '--variables RADIX_ZONE=dev'
