name: TEST Pull request
on:
  pull_request:
    branches:
    - main

jobs:
  matrix_prep:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4
      - id: set-matrix
        run: |
          branchName=$(echo '${{ github.ref }}' | sed 's,refs/heads/,,g')  
          
          matrix=$(jq --arg ref "${{ github.ref }}" 'map( 
              . | select((.runOn==$ref or (.runOn=="always"))
          )' targets.json)                
          echo "matrix={\"include\":$(echo $matrix)}" >> $GITHUB_OUTPUT

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: [matrix-prep]
    #    strategy:
#      matrix:
#   # if: ${{matrix.test.if}}
    steps:
    - run: echo ${{needs.matrix-prep.matrix}} #${{matrix.test.msg}}
