name: TEST Pull request
on:
  pull_request:
    branches:
    - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        target:
          - name: "dev"
            run: always
            acr-name: "radixdev"
            client-id: "1a292b18-2960-49a5-b429-c8a50349b5eb"
            subscription-id: "16ede44b-1f74-40a5-b428-46cca9a5741b"

          - name: "playground"
            run: always
            acr-name: "radixdev"
            client-id: "1a292b18-2960-49a5-b429-c8a50349b5eb"
            subscription-id: "16ede44b-1f74-40a5-b428-46cca9a5741b"

          - name: "platform"
            run: "refs/heads/release"
            acr-name: "radixprod"
            client-id: "d1ee58e8-5896-48d9-a777-5418c3df9a58"
            subscription-id: "ded7ca41-37c8-4085-862f-b11d21ab341a"

          - name: "c2"
            run: "refs/heads/release"
            acr-name: "radixc2prod"
            client-id: "d1ee58e8-5896-48d9-a777-5418c3df9a58"
            subscription-id: "ded7ca41-37c8-4085-862f-b11d21ab341a"

    steps:
    - run: echo "${{matrix.run}}"
    - if: matrix.run == "always" || matrix.run == ${{GITHUB_REF}}
      run: echo "${{matrix.name}} ${{matrix.acr-name}}"
