name: TEST Pull request
on:
  pull_request:
    branches:
    - main

jobs:
  matrix-prep:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4
      - id: set-matrix
        env:
          REF: ${{ github.ref }}
        run: |        
          matrix=$(jq --arg ref "$REF" 'map( . | select((.runOn==$ref) or (.runOn=="always")))' targets.json)
          echo "matrix={\"include\":$(echo $matrix)}" >> $GITHUB_OUTPUT

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: [matrix-prep]
    #    strategy:
#      matrix:
#   # if: ${{matrix.test.if}}
    steps:
    - run: echo ${{needs.matrix-prep.matrix}} #${{matrix.test.msg}}
